//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp8
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;


    public partial class MedicinaEntities : DbContext
    {
        private static MedicinaEntities _context; 

        public MedicinaEntities()
            : base("name=MedicinaEntities")
        {
        }

        public static MedicinaEntities GetContext() 
        { 
            if (_context == null)
                _context = new MedicinaEntities();

            return _context; 
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WindowsFormsApp8.Models.Doctor> Doctor { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<MedCard> MedCard { get; set; }
        public virtual DbSet<Pacient> Pacient { get; set; }
        public virtual DbSet<Pasport> Pasport { get; set; }
        public virtual DbSet<Polis> Polis { get; set; }
        public virtual DbSet<PolisCompany> PolisCompany { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_Event> Type_Event { get; set; }
        public virtual DbSet<Visit> Visit { get; set; }
    }
}
